### PR TITLE
Small Typo Fix class-wizard.xml

### PR DESCRIPTION
**Pull request by Chessepuff**
Tiny typo I saw. The regular description in this file says 6th level but the sheet description says 5th level. Checked the PHB to confirm it is 6th level.

### CODE REVIEW

**Comment by NickVendel** [comment]
You misread the description

**Comment by NickVendel** [comment]
`and none of the slots can be 6th level or higher.` is the same as `you can choose expended spell slots up to 5th level to recover.`

**Comment by Chessepuff** [comment]
You are correct sir apologies.

**Comment by NickVendel** [comment]
no worries, have fun with the app

**Pull request closed without merging**
