### PR TITLE
[MISC] Vision Rework

### PR DESCRIPTION
**Pull request by kgirtxd**

### CODE REVIEW

**Comment by NickVendel** [comment]
okay, will it break characters? There are features that give visions

**Comment by kgirtxd** [comment]
> okay, ~will it break characters~ will it display base 0 range for visions that you get from features?

Characters with superior darkvision will receive a minor load error as the client removes any normal darkvision due to the new requirements.  Granting Tremorsense, Truesight, Blindsight, or the new lesser darkvision will show a 0ft range since there is no standard range for these features.  I did a search for everything that currently grants them and added a new bonus="base" range stat for each instance.

**Comment by NickVendel** [comment]
But there's 0 features here... i mean, i can imagine some of them already have `base` bonus, especially for those that give Darkvision, but i'm not sure if there are other such things... i guess if there is we can fix it later

**Review by NickVendel — APPROVED** [review]
we should warn people about potential breaking of characters with Superior Darkvision though

**Review by AngryGuineaPig — APPROVED** [review]

**Pull request merged**
