### PR TITLE
[TCOE] Add Artificer Class and Move Infusions to Spell List

### PR DESCRIPTION
**Pull request by cory2012**
Created Artificer Base Class and Archetypes
Removed original Archetype file
Added infusions as spells
Added infusion items descriptions
Created Companion cards for Artificer features
Created items for infusions and Artificer features

Corrected typo found in Xanathars item file

### CODE REVIEW

**Comment by cory2012** [comment]
Hey guys, I have experience coding but have never done anything on github or this project. Please let me know if I did anything wrong.

**Comment by NickVendel** [comment]
@cory2012 to speed up communication do you have Discord and/or use our server?

**Comment by cory2012** [comment]
My discord username is DeltaSkittles

**Comment by aurorabuilderlegacy** [comment]
As it is now the team feels that it is not a wise decision to move artificer infusions to the spell tab using your interpretation.  We agree that the current system is not ideal, and we will do some testing to hopefully come up with a more stable and user-friendly method.

Previously you brought up the point of PHB+1 for AL and why we need to add Artificer and reprinted archetypes to the TCoE source.  For the sake of not having the same content in multiple places, the team had decided to leave it within the ERLW source.  Once TCoE work is complete, if you would like to gain a few supporters then request that we make a poll we would be happy to do so.  Then we can see how the community feels about moving, leaving, or copying artificer between the sources and act accordingly.

Thank you for pointing out the issue with the Armor ID.  Unfortunately changing any IDs will cause all characters that have the armor to lose/reselect it.  We are going to hold off until we can warn the community and fix other issues at the same time.  We are currently listing all issues like this under issue #47.

Thank you for taking interest in the project and we look forward to your future contributions.

**Pull request closed without merging**
