### PR TITLE
Moved optional class features to Build/Class tab

### PR DESCRIPTION
**Pull request by alsimoneau**
Moved Tasha's optional class feature to into the class tab
Added global option to disable these features

### CODE REVIEW

**Comment by AngryGuineaPig** [comment]
The way we've done OCF was put to a vote in the discord server when we were first making the content files. We're not going to change it.

**Comment by kgirtxd** [comment]
The idea here was if homebrew or WoTC added more OCF then they can be added without touching the core classes. Also having an unknown number of optional selects just clutters the build tabs

**Comment by alsimoneau** [comment]
Since some feature necessitated added requirements in the core classes anyways (specifically the ranger and cleric) and it was a small change to support, it seemed to be a more intuitive user experience. Moreover, the equipment option is a pain to go through.

The global option toggle was added to reduce clutter in characters not interested by theses options.

**Comment by kgirtxd** [comment]
I will start by saying that doing it the way you are proposing was originally considered but due to the rigid nature it makes it difficult to add future and homebrew content without constantly touching core which we would like to avoid and therefore we looked into other options.

As far as user experience.  I agree that putting them in equipment may not be the most intuitive but everyone that has had issues finding it was happy once we pointed it out and reminded them to equip the item.  For the bigger picture, this has opened up the ability for anyone to make their own OCFs without conflicing with the main repository.

To your point about global character options to hide unnecessary options.  That section of the app was written in a way such that it quickly becomes bloated in itself and it is hard to use for people with low resolution monitors.  We try to avoid it unless it is necessary.  However it might not be a bad idea to add something there to point people to the equipment section for optional stuff.

To your point about ranger and cleric. First the cleric change required touching every cleric subclass from all sources, so that was rather large.  The ranger was thankfully just the one file.  That being said we implemented grants that allow us to turn off features when needed.  This is soon to be expanded to all classes and subclasses for better future proofing.

As I said before, if you disagree with the choices we made then you are free to make a fork with your changes that you and your friends can use.

**Comment by NickVendel** [comment]
I'll add to that, since i'm the one who did most of the CFV/OCF stuff.
The main reason why i thought Equipment section would be a better way to do OCF than doing it through Option (beside my boundless hatred of how it's codded and works), was because OCFs is not just an Optional Rule or something like that, it's not like if you decide to get one you must choose other ones too, moreover DMs can decide to allow only some of them, so in those cases optional selects would clutter menus for no reason.

And obviously if you prefer it being an Option and having no problem with codding it yourself (though, Eterean did his version that has the same logic, so in cases where people would like that option, we usually point at his version, even though it has its share of issues too), then you're free to make and use it the way you like it. But for most users, i believe doing it through Equipment section is as good if not better than using selects.

Also, if you do plan on using your version in combination with our repo (basically by placing your files into user folder), check Beast Master's feature, i checked it and it doesn't seem to work, probably because `Ranger’s Companion` is already granted from the Archetype.

**Comment by alsimoneau** [comment]
Thank you for the feedback.

**Pull request closed without merging**
